### ISSUE TITLE
Разработка модуля управления драйвером приводов

### ISSUE THREAD

**Issue by KaiL4eK** [KaiL4eK/tigra_project#1]
Необходимо разработать модуль задания мощности для привода хода, рулевого привода и системы тормоза

**Comment by serykhelena** [comment]
Есть несколько вопросов: 
1. В каких диапазонах должна изменяться ширина ШИМ при управлении рулём и тормозом?
2. Зачем дискретный выход при управлении тормозом? 
3. Зачем дискретный выход при управлении ведущими колёсами? 
4. При использовании функции для указания направления вращения, а именно drControlSetMotorDirection, что она должна делать с физической точки зрения?

**Comment by DenF2412** [comment]
1 Тормоз и рулевая система приводятся в движение с помощью двигателей постоянного тока.
Пока эти двигатели никто детально не изучал с точки зрения обоснования выбора частоты. Думаю, что для ШИМ можно начать с 1 кГц. Ширина импульса будет изменяться от некоторого минимального значения (определим его экспериментально) до 100%. Шаг изменения ширины импульса должен быть не более 10 мкс (из расчета не менее 100 значений на весь диапазон). Есть вероятность, что несущую частоту придется уменьшить до 100 Гц. 
2, 3 С помощью дискретного выхода мы сможем задать направление вращения (с помощью ШИМ мы управляем скоростью вращения)
4 Как минимум эта функция должна выставить значение дискретного выхода для управления направлением движения. как максимум проверить, что смена направления происходит при нулевой скважности ШИМ, Переключение направления вращения в движении - режим активного торможения => могут возникнуть большие токи, которые могут спалить двигатель и/или преобразователь.

**Comment by KaiL4eK** [comment]
Полагаю, 4й ответ может быть отнесен на верхний уровень, в остальном согласен

**Comment by serykhelena** [comment]
Модуль ШИМ, ЦАП и цифровые выходы для задания направления работают (ветка [ll_driver_control]), ветки пока не сливались

**Comment by KaiL4eK** [comment]
Перенесен в полный Done, так как апробации с железом провести невозможно, будет переход на новый в #13
