### ISSUE TITLE
Разработка драйвера датчиков руля

### ISSUE THREAD

**Issue by KaiL4eK** [KaiL4eK/tigra_project#3]

**Comment by serykhelena** [comment]
Для этого драйвера нужно только настроить АЦП? Или ещё что-то?

**Comment by KaiL4eK** [comment]
Как я понял, если все заложено на АЦП, то можно объединить данную задачу с #10, так как в обоих задачах нужен АЦП для системы руля (положение и усилие)

**Comment by serykhelena** [comment]
Да, хорошая идея

**Comment by KaiL4eK** [comment]
Может в таком случае сделать один модуль на обе задачи, назвать steer sensors, а функции будут на получение steerPressPower и steerPosition?
В таком случае здесь можно использовать отдельный АЦП (например первый), а в моем модуле оставить второй
Далее еще свободен третий, но если надо будет ужаться - будем объединять

**Comment by KaiL4eK** [comment]
В #10 остается непонятным, сколько там датчиков (1 или 2), тем не менее пока точно известно про датчик тока

**Comment by KaiL4eK** [comment]
@serykhelena я расширяю данную задачу до двух каналов АЦП?

**Comment by serykhelena** [comment]
Да, давай

**Comment by serykhelena** [comment]
АЦП работает, сейчас используется два канала, самый простой тест сделан.
